# Reference: https://docs.docker.com/reference/compose-file/
name: min-timespan-delivery

services:
  devcontainer:
    command: bash -c "sleep infinity"
    container_name: devcontainer
    environment:
      RUST_BACKTRACE: "1"
    image: ubuntu:24.04
    volumes:
      - ..:/workspaces/min-timespan-delivery
    working_dir: /workspaces/min-timespan-delivery
